"""Parity test: Python corrected calculator vs the base-R reference model.

The R reference outputs live in backend/tests/thrace_reference/ (generated by
backend/scripts/thrace_r_reference.R). The raw input CSVs live in the gitignored
Thrace/New items/THRACE R version folder. If the input CSVs are unavailable the test
is skipped (the committed R fixtures alone are not enough to rebuild all_data).
"""
import csv
import math
from pathlib import Path

import pytest

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from routers.thrace_calculator import build_all_data, get_freedom_data  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
R_DIR = ROOT / "Thrace" / "New items" / "THRACE R version"
REF_DIR = Path(__file__).resolve().parent / "thrace_reference"

CASES = [("FMD", "BOV", "GR"), ("PPR", "SR", "GR"), ("LSD", "LR", "BG")]

FLOAT_COLS = ["cse_clin", "cse_sero", "sse", "pintro", "prior", "posterior", "edsse"]
INT_COLS = ["animals", "herds", "sero", "clin", "seropos", "clinpos"]
ABS_TOL = 1e-6


def _read_csv(path, delimiter=","):
    with open(path, newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f, delimiter=delimiter))


def _build_rows():
    """Join factivities + geography from the R input CSVs into calculator row dicts."""
    fact = _read_csv(R_DIR / "factivities.csv")
    epi = {r["epiunitID"]: r for r in _read_csv(R_DIR / "epiunits.csv")}
    dist = {r["districtID"]: r for r in _read_csv(R_DIR / "districts.csv")}
    prov = {r["provinceID"]: r for r in _read_csv(R_DIR / "provinces.csv")}
    nat = {r["nationID"]: r for r in _read_csv(R_DIR / "nations_old.csv")}

    rows = []
    for f in fact:
        e = epi.get(f["epiunitID"])
        if not e:
            continue
        d = dist.get(e["districtID"])
        if not d:
            continue
        p = prov.get(d["provinceID"])
        if not p:
            continue
        n = nat.get(p["nationID"])
        if not n:
            continue
        row = dict(f)
        row["epiunitID"] = int(f["epiunitID"])
        row["country"] = n["three_letter_code"]
        row["district_name"] = d["district_name"]
        row["province_name"] = p["province_name"]
        rows.append(row)
    return rows


@pytest.fixture(scope="module")
def all_data():
    if not R_DIR.exists() or not (R_DIR / "factivities.csv").exists():
        pytest.skip("R input CSVs not available (gitignored Thrace/New items folder)")
    return build_all_data(_build_rows(), strict_risk=True)


def _fnum(v):
    if v is None or v == "" or v == "NA":
        return None
    try:
        f = float(v)
    except ValueError:
        return None
    return None if math.isnan(f) else f


@pytest.mark.parametrize("dz,sp,reg", CASES)
def test_parity(all_data, dz, sp, reg):
    ref_path = REF_DIR / f"ref_{dz}_{sp}_{reg}.csv"
    assert ref_path.exists(), f"missing reference fixture {ref_path}"
    ref = _read_csv(ref_path)

    out = get_freedom_data(sp, dz, reg, all_data)
    out_by = {(int(o["year"]), int(o["month"])): o for o in out}

    assert len(out) == len(ref), f"{dz}/{sp}/{reg}: month count {len(out)} != R {len(ref)}"

    for rr in ref:
        key = (int(rr["year"]), int(rr["month"]))
        assert key in out_by, f"{dz}/{sp}/{reg}: month {key} missing in Python output"
        o = out_by[key]

        for col in INT_COLS:
            assert int(o[col]) == int(float(rr[col])), \
                f"{dz}/{sp}/{reg} {key} {col}: py={o[col]} r={rr[col]}"

        for col in FLOAT_COLS:
            rv = _fnum(rr[col])
            pv = o.get(col)
            if isinstance(pv, float) and math.isnan(pv):
                pv = None
            if rv is None:
                assert pv is None, f"{dz}/{sp}/{reg} {key} {col}: py={pv} r=None"
            else:
                assert pv is not None, f"{dz}/{sp}/{reg} {key} {col}: py=None r={rv}"
                assert abs(pv - rv) <= ABS_TOL, \
                    f"{dz}/{sp}/{reg} {key} {col}: py={pv} r={rv} diff={abs(pv-rv)}"
